<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        Question::query()->delete();

        $questions = [
            // ==========================================
            // CARD A: Identitas Dasar & Ikon Kota (10 Soal)
            // ==========================================
            [
                'card' => 'A',
                'question' => 'Apa nama ibu kota / pusat pemerintahan Kabupaten Tabalong?',
                'option_a' => 'Tanjung',
                'option_b' => 'Murung Pudak',
                'option_c' => 'Kelua',
                'option_d' => 'Muara Uya',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Kabupaten Tabalong dijuluki sebagai Kota...',
                'option_a' => 'Bumi Tambun Bungai',
                'option_b' => 'Bumi Saraba Kawa',
                'option_c' => 'Bumi Bahalap',
                'option_d' => 'Bumi Sai Jaan',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Monumen kebanggaan yang menjadi ikon utama Kota Tanjung di Kabupaten Tabalong adalah...',
                'option_a' => 'Tugu Khatulistiwa',
                'option_b' => 'Tugu Pahlawan',
                'option_c' => 'Tugu Obor Pancasila',
                'option_d' => 'Tugu Jam Kota',
                'correct_answer' => 'C',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Istilah atau moto "Saraba Kawa" berasal dari bahasa...',
                'option_a' => 'Dayak',
                'option_b' => 'Bugis',
                'option_c' => 'Indonesia',
                'option_d' => 'Banjar',
                'correct_answer' => 'D',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Kabupaten Tabalong terletak di provinsi...',
                'option_a' => 'Kalimantan Selatan',
                'option_b' => 'Kalimantan Tengah',
                'option_c' => 'Kalimantan Timur',
                'option_d' => 'Kalimantan Barat',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Kobaran api pada Tugu Obor Pancasila melambangkan kekayaan sumber daya energi Tabalong berupa...',
                'option_a' => 'Perkebunan',
                'option_b' => 'Minyak Bumi dan Gas',
                'option_c' => 'Perikanan',
                'option_d' => 'Pertanian',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Taman kota di pusat Kota Tanjung yang menjadi ruang terbuka hijau dan tempat santai warga adalah...',
                'option_a' => 'Taman Bunga',
                'option_b' => 'Taman Monas',
                'option_c' => 'Taman Giat Tanjung',
                'option_d' => 'Taman Kota Ria',
                'correct_answer' => 'C',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Secara geografis, Kabupaten Tabalong terletak di bagian paling ... dari Provinsi Kalimantan Selatan.',
                'option_a' => 'Selatan',
                'option_b' => 'Barat',
                'option_c' => 'Timur',
                'option_d' => 'Utara',
                'correct_answer' => 'D',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Bunga khas lokal yang sering ditemui dan menghiasi taman-taman kota Tanjung adalah...',
                'option_a' => 'Bunga Anggrek Hitam / Khas Banjar',
                'option_b' => 'Bunga Tulip',
                'option_c' => 'Bunga Sakura',
                'option_d' => 'Bunga Edelweiss',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'A',
                'question' => 'Ikon pintu gerbang perbatasan Tabalong yang menghubungkan Kalsel dengan Kaltim berada di kawasan...',
                'option_a' => 'Kelua',
                'option_b' => 'Jaro / Muara Uya',
                'option_c' => 'Mabuun',
                'option_d' => 'Pugaan',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Identitas Dasar & Ikon Kota',
                'difficulty' => 'Mudah',
            ],

            // ==========================================
            // CARD B: Moto, Geografi & Julukan (10 Soal)
            // ==========================================
            [
                'card' => 'B',
                'question' => 'Apa arti dari moto "Saraba Kawa"?',
                'option_a' => 'Sangat Luas',
                'option_b' => 'Serba Bisa / Sanggup Menyelesaikan Tugas',
                'option_c' => 'Selalu Damai',
                'option_d' => 'Pantang Menyerah',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Kabupaten Tabalong berbatasan langsung di sebelah utara dengan provinsi...',
                'option_a' => 'Jawa Timur',
                'option_b' => 'Sulawesi Selatan',
                'option_c' => 'Kalimantan Tengah dan Kalimantan Timur',
                'option_d' => 'Kalimantan Barat',
                'correct_answer' => 'C',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Nama Kabupaten Tabalong diambil dari nama sungai utama yang mengalir di wilayah ini, yaitu...',
                'option_a' => 'Sungai Barito',
                'option_b' => 'Sungai Martapura',
                'option_c' => 'Sungai Mahakam',
                'option_d' => 'Sungai Tabalong',
                'correct_answer' => 'D',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Warna dasar dari lambang daerah Kabupaten Tabalong yang melambangkan kesuburan adalah...',
                'option_a' => 'Hijau',
                'option_b' => 'Merah',
                'option_c' => 'Biru',
                'option_d' => 'Kuning',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Bandar udara (bandara) yang terdapat di Kabupaten Tabalong adalah...',
                'option_a' => 'Bandara Syamsudin Noor',
                'option_b' => 'Bandara Warukin',
                'option_c' => 'Bandara Sepinggan',
                'option_d' => 'Bandara Tjilik Riwut',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Rumah sakit umum daerah (RSUD) terbesar milik Pemerintah Kabupaten Tabalong adalah...',
                'option_a' => 'RSUD Ulin',
                'option_b' => 'RSUD Ansari Saleh',
                'option_c' => 'RSUD H. Badaruddin Kasim',
                'option_d' => 'RSUD Sultan Suriansyah',
                'correct_answer' => 'C',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Kota Tanjung terkenal memiliki suasana kota yang bersih dan rapi. Julukan penghargaan kebersihan kota ini adalah...',
                'option_a' => 'Kota Kencana',
                'option_b' => 'Kota Bersolek',
                'option_c' => 'Kota Bunga',
                'option_d' => 'Kota Adipura',
                'correct_answer' => 'D',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Angkutan gratis untuk anak sekolah dan masyarakat umum yang dihadirkan Pemkab Tabalong dinamakan...',
                'option_a' => 'Langsak Manis',
                'option_b' => 'Mobil Idaman',
                'option_c' => 'Trans Tabalong',
                'option_d' => 'Bus Kota',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Wilayah Tabalong berada di posisi strategis karena menjadi daerah penyangga untuk kawasan...',
                'option_a' => 'Ibu Kota Nusantara (IKN)',
                'option_b' => 'Kawasan Industri Jabodetabek',
                'option_c' => 'Segitiga Emas Sumatra',
                'option_d' => 'Kawasan Bebas Batam',
                'correct_answer' => 'A',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],
            [
                'card' => 'B',
                'question' => 'Batas sebelah selatan Kabupaten Tabalong berbatasan langsung dengan Kabupaten...',
                'option_a' => 'Banjar',
                'option_b' => 'Hulu Sungai Utara (HSU) & Balangan',
                'option_c' => 'Tanah Laut',
                'option_d' => 'Kotabaru',
                'correct_answer' => 'B',
                'points' => 100,
                'category' => 'Moto, Geografi & Julukan',
                'difficulty' => 'Mudah',
            ],

            // ==========================================
            // CARD C: Tempat Umum & Fasilitas Publik (10 Soal)
            // ==========================================
            [
                'card' => 'C',
                'question' => 'Kompleks olahraga terpadu dan stadion utama yang berlokasi di Pembataan, Tabalong adalah...',
                'option_a' => 'Stadion 17 Mei',
                'option_b' => 'Stadion Demang Lehman',
                'option_c' => 'Stadion Pembataan / Tanjung Puri',
                'option_d' => 'Stadion Gelora Bung Karno',
                'correct_answer' => 'C',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Pasar tradisional terbesar di Kabupaten Tabalong yang berlokasi di Tanjung adalah...',
                'option_a' => 'Pasar Bauntung',
                'option_b' => 'Pasar Sentral',
                'option_c' => 'Pasar Kaget',
                'option_d' => 'Pasar Usaha Tani / Pasar Tanjung',
                'correct_answer' => 'D',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Pusat kegiatan keagamaan dan masjid agung terbesar di Kabupaten Tabalong adalah...',
                'option_a' => 'Masjid Agung Ash-Shirathal Mustaqim',
                'option_b' => 'Masjid Raya Sabilal Muhtadin',
                'option_c' => 'Masjid Al-Akbar',
                'option_d' => 'Masjid Miftahul Jannah',
                'correct_answer' => 'A',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Taman wisata air / waterboom modern yang ada di daerah Murung Pudak Tabalong adalah...',
                'option_a' => 'Water Park Tanjung',
                'option_b' => 'Waterboom Tirta Kencana',
                'option_c' => 'Waterboom Pembataan',
                'option_d' => 'Wisata Air Barito',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Gedung pusat seni dan pertunjukan budaya masyarakat Tabalong dinamakan...',
                'option_a' => 'Gedung Usman Ismail',
                'option_b' => 'Gedung Wisrabawa / Gedung Seni Budaya',
                'option_c' => 'Gedung Pancasila',
                'option_d' => 'Gedung Pemuda',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Riam Air Terjun Lano yang terkenal indah berada di kecamatan...',
                'option_a' => 'Jaro',
                'option_b' => 'Haruai',
                'option_c' => 'Muara Uya',
                'option_d' => 'Bintang Ara',
                'correct_answer' => 'C',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Wisata Gua Liang Kantin berada di kawasan wilayah kecamatan...',
                'option_a' => 'Jaro',
                'option_b' => 'Pugaan',
                'option_c' => 'Tanta',
                'option_d' => 'Muara Uya',
                'correct_answer' => 'D',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Hutan kota yang berfungsi sebagai paru-paru kota di Tanjung dinamakan...',
                'option_a' => 'Hutan Kota Tanjung Puri',
                'option_b' => 'Hutan Kota Murung Pudak',
                'option_c' => 'Hutan Mangrove',
                'option_d' => 'Hutan Pine',
                'correct_answer' => 'A',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Wisata Danau Burum di Tabalong sering dijadikan destinasi masyarakat untuk...',
                'option_a' => 'Selancar Angin',
                'option_b' => 'Memancing dan Bersantai',
                'option_c' => 'Arung Jeram Ekstrem',
                'option_d' => 'Penyulingan Minyak',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'C',
                'question' => 'Kawasan Ruang Terbuka Hijau (RTH) Mabuun menjadi pusat keramaian warga karena terdapat panggung terbuka dan kawasan...',
                'option_a' => 'Pelabuhan Laut',
                'option_b' => 'Stasiun Kereta',
                'option_c' => 'Kuliner & UMKM',
                'option_d' => 'Bandar Udara International',
                'correct_answer' => 'C',
                'points' => 200,
                'category' => 'Tempat Umum & Fasilitas Publik',
                'difficulty' => 'Mudah - Menengah',
            ],

            // ==========================================
            // CARD D: Kesenian, Kuliner & Budaya Populer (10 Soal)
            // ==========================================
            [
                'card' => 'D',
                'question' => 'Makanan khas Tabalong berupa olahan ikan yang dimasak dengan kuah santan kuning kental dinamakan...',
                'option_a' => 'Paliat',
                'option_b' => 'Gangan Asam',
                'option_c' => 'Ketupat Kandangan',
                'option_d' => 'Soto Banjar',
                'correct_answer' => 'A',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Kuah dari masakan khas Paliat memiliki cita rasa gurih khas karena mengandalkan campuran santan dan...',
                'option_a' => 'Kecap Manis',
                'option_b' => 'Asam Mampalam (Mempelam)',
                'option_c' => 'Kuah Kacang',
                'option_d' => 'Petis Ikan',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Ikan utama yang paling populer disajikan dalam masakan Paliat khas Tabalong adalah...',
                'option_a' => 'Ikan Bandeng',
                'option_b' => 'Ikan Gurame',
                'option_c' => 'Ikan Baung / Patin / Salap',
                'option_d' => 'Ikan Salmon',
                'correct_answer' => 'C',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Tari tradisional Banjar yang sering ditampilkan untuk menyambut tamu kehormatan di Tabalong adalah...',
                'option_a' => 'Tari Pendet',
                'option_b' => 'Tari Piring',
                'option_c' => 'Tari Saman',
                'option_d' => 'Tari Baksa Kembang',
                'correct_answer' => 'D',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Kerajinan anyaman khas masyarakat suku Dayak Deah di Tabalong terbuat dari bahan alami berupa...',
                'option_a' => 'Rotan dan Purun',
                'option_b' => 'Plastik',
                'option_c' => 'Eceng Gondok',
                'option_d' => 'Kain Perca',
                'correct_answer' => 'A',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Festival kebudayaan tahunan yang menampilkan atraksi seni budaya lokal di Tabalong dinamakan...',
                'option_a' => 'Tabalong Carnival',
                'option_b' => 'Tabalong Ethnic Festival (TEF)',
                'option_c' => 'Festival Danau Sentarum',
                'option_d' => 'Pesta Rakyat Banjar',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Musik tradisional yang dimainkan mengiringi syair-syair pujian keagamaan di wilayah Tabalong adalah...',
                'option_a' => 'Gamelan Jawa',
                'option_b' => 'Angklung',
                'option_c' => 'Rebana / Terbang Mawlid',
                'option_d' => 'Kolintang',
                'correct_answer' => 'C',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Kue/wadai tradisional Banjar khas Tabalong yang bertekstur lembut dan manis dari gula merah adalah...',
                'option_a' => 'Bika Ambon',
                'option_b' => 'Kue Lapis Legit',
                'option_c' => 'Bakpia',
                'option_d' => 'Wadai Bingka & Amparan Tatak',
                'correct_answer' => 'D',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Minuman segar tradisional yang sering dijajakan pendamping kuliner khas di Tanjung adalah...',
                'option_a' => 'Es Limau Kuit / Es Kelapa Muda',
                'option_b' => 'Es Matcha',
                'option_c' => 'Boba Tea',
                'option_d' => 'Es Coklat Kentol',
                'correct_answer' => 'A',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],
            [
                'card' => 'D',
                'question' => 'Motif kain Sasirangan khas Tabalong yang terinspirasi dari kearifan lokal daerah dinamakan motif...',
                'option_a' => 'Batik Mega Mendung',
                'option_b' => 'Sasirangan Ringgit / Obor Tabalong',
                'option_c' => 'Tenun Ikat Ikat',
                'option_d' => 'Ulos Batak',
                'correct_answer' => 'B',
                'points' => 200,
                'category' => 'Kesenian, Kuliner & Budaya Populer',
                'difficulty' => 'Mudah - Menengah',
            ],

            // ==========================================
            // CARD E: Tanggal Penting & Sejarah Pembentukan (10 Soal)
            // ==========================================
            [
                'card' => 'E',
                'question' => 'Hari Jadi / HUT Kabupaten Tabalong diperingati setiap tanggal...',
                'option_a' => '10 November',
                'option_b' => '17 Agustus',
                'option_c' => '1 Desember',
                'option_d' => '24 September',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Kabupaten Tabalong secara resmi dibentuk pada tahun berapa?',
                'option_a' => '1950',
                'option_b' => '1971',
                'option_c' => '1980',
                'option_d' => '1965',
                'correct_answer' => 'D',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Dasar hukum pembentukan Kabupaten Tabalong adalah Undang-Undang Nomor...',
                'option_a' => 'UU No. 8 Tahun 1965',
                'option_b' => 'UU No. 12 Tahun 1950',
                'option_c' => 'UU No. 22 Tahun 1999',
                'option_d' => 'UU No. 32 Tahun 2004',
                'correct_answer' => 'A',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Sebelum berdiri sebagai kabupaten otonom, wilayah Tabalong merupakan bagian dari Kabupaten...',
                'option_a' => 'Hulu Sungai Selatan (HSS)',
                'option_b' => 'Hulu Sungai Utara (HSU)',
                'option_c' => 'Banjar',
                'option_d' => 'Barito Kuala',
                'correct_answer' => 'B',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Bupati pertama yang memimpin Kabupaten Tabalong pada awal pembentukannya adalah...',
                'option_a' => 'H. Dandang',
                'option_b' => 'M. Noor',
                'option_c' => 'Usman Dundrung',
                'option_d' => 'Badaruddin Kasim',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Panitia Penuntut Kabupaten Tabalong (PPKT) dahulu berjuang memisahkan diri demi mempercepat...',
                'option_a' => 'Perdagangan Luar Negeri',
                'option_b' => 'Pembentukan Provinsi Baru',
                'option_c' => 'Eksplorasi Minyak',
                'option_d' => 'Pembangunan dan Pelayanan Publik',
                'correct_answer' => 'D',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Kantor Bupati Tabalong berlokasi di jalan protokol bernama...',
                'option_a' => 'Jl. A. Yani',
                'option_b' => 'Jl. Pangeran Antasari',
                'option_c' => 'Jl. Jend. Sudirman',
                'option_d' => 'Jl. Pahlawan',
                'correct_answer' => 'A',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Tokoh pejuang pergerakan daerah yang menjadi Ketua Panitia Penuntut Kabupaten Tabalong adalah...',
                'option_a' => 'Usman Dundrung',
                'option_b' => 'H. Badaruddin Kasim',
                'option_c' => 'Penghulu Rashid',
                'option_d' => 'Pangeran Hidayatullah',
                'correct_answer' => 'B',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Pahlawan pejuang lokal dari tanah Tabalong yang gigih melawan penjajahan Belanda adalah...',
                'option_a' => 'Pangeran Diponegoro',
                'option_b' => 'Pattimura',
                'option_c' => 'Penghulu Rashid',
                'option_d' => 'Teuku Umar',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'E',
                'question' => 'Rapat paripurna pengesahan Hari Jadi Kabupaten Tabalong dilaksanakan oleh legislatif daerah pada...',
                'option_a' => 'DPRD Kabupaten Kalsel',
                'option_b' => 'DPR RI',
                'option_c' => 'MPR RI',
                'option_d' => 'DPRD Kabupaten Tabalong',
                'correct_answer' => 'D',
                'points' => 300,
                'category' => 'Tanggal Penting & Sejarah Pembentukan',
                'difficulty' => 'Menengah',
            ],

            // ==========================================
            // CARD F: Suku Asli, Adat & Tradisi (10 Soal)
            // ==========================================
            [
                'card' => 'F',
                'question' => 'Suku asli Dayak yang mendiami wilayah utara Kabupaten Tabalong (seperti di Upau) adalah...',
                'option_a' => 'Dayak Deah',
                'option_b' => 'Dayak Ngaju',
                'option_c' => 'Dayak Kenyah',
                'option_d' => 'Dayak Iban',
                'correct_answer' => 'A',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Upacara adat syukuran panen padi khas masyarakat Dayak Deah di Tabalong dikenal dengan nama...',
                'option_a' => 'Mappanretasi',
                'option_b' => 'Malaman / Gawi Ea',
                'option_c' => 'Erau',
                'option_d' => 'Naik Dango',
                'correct_answer' => 'B',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Balai adat Dayak yang terkenal di Kabupaten Tabalong terletak di Desa...',
                'option_a' => 'Kampung Minyak',
                'option_b' => 'Pembataan',
                'option_c' => 'Gunung Batu / Kinarum',
                'option_d' => 'Kelua',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Bahasa daerah yang paling dominan digunakan dalam percakapan sehari-hari di Kabupaten Tabalong adalah...',
                'option_a' => 'Bahasa Jawa',
                'option_b' => 'Bahasa Bugis',
                'option_c' => 'Bahasa Madura',
                'option_d' => 'Bahasa Banjar & Bahasa Dayak',
                'correct_answer' => 'D',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Baju adat khas masyarakat Banjar yang dipakai pada acara pernikahan adat di Tabalong dinamakan...',
                'option_a' => 'Baamar Galung / Bagajah Gamuling',
                'option_b' => 'Ulos',
                'option_c' => 'Baju Bodo',
                'option_d' => 'Kebaya Encim',
                'correct_answer' => 'A',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Ritual adat pengobatan atau penyucian desa pada masyarakat Dayak di Tabalong disebut...',
                'option_a' => 'Ngaben',
                'option_b' => 'Balian / Belian',
                'option_c' => 'Sekaten',
                'option_d' => 'Ruwatan',
                'correct_answer' => 'B',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Tari tradisional khas Dayak Deah yang melambangkan keberanian dan pertahanan diri adalah...',
                'option_a' => 'Tari Kecak',
                'option_b' => 'Tari Jaipong',
                'option_c' => 'Tari Mandau / Kancet Papatai',
                'option_d' => 'Tari Piring',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Perkampungan adat Dayak di Kabupaten Tabalong yang dijaga keasriannya sebagai destinasi budaya adalah...',
                'option_a' => 'Desa Mabuun',
                'option_b' => 'Desa Murung Pudak',
                'option_c' => 'Desa Pugaan',
                'option_d' => 'Desa Kinarum & Desa Upau',
                'correct_answer' => 'D',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Senjata tradisional suku Dayak di Tabalong yang berhiaskan ukiran khas adalah...',
                'option_a' => 'Mandau',
                'option_b' => 'Keris',
                'option_c' => 'Rencong',
                'option_d' => 'Kujang',
                'correct_answer' => 'A',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],
            [
                'card' => 'F',
                'question' => 'Alat musik tiup tradisional khas Dayak yang terbuat dari bambu dan labu kering adalah...',
                'option_a' => 'Sitar',
                'option_b' => 'Kordeon',
                'option_c' => 'Sape / Kledi',
                'option_d' => 'Gendang',
                'correct_answer' => 'C',
                'points' => 300,
                'category' => 'Suku Asli, Adat & Tradisi',
                'difficulty' => 'Menengah',
            ],

            // ==========================================
            // CARD G: Komoditas Usaha & Sumber Daya Alam (10 Soal)
            // ==========================================
            [
                'card' => 'G',
                'question' => 'Kabupaten Tabalong merupakan salah satu daerah penghasil tambang terbesar di Kalsel, yaitu...',
                'option_a' => 'Tembaga & Biji Besi',
                'option_b' => 'Batu Bara & Minyak Bumi',
                'option_c' => 'Emas & Perak',
                'option_d' => 'Timah & Nikel',
                'correct_answer' => 'B',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Perusahaan eksplorasi minyak bumi peninggalan era kolonial hingga kini yang beroperasi di Tabalong adalah...',
                'option_a' => 'PT Freeport',
                'option_b' => 'PT Timah',
                'option_c' => 'PT Pertamina EP Asset 5 Field Tanjung',
                'option_d' => 'PT Aneka Tambang',
                'correct_answer' => 'C',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Salah satu perusahaan tambang batu bara raksasa yang beroperasi di wilayah Kabupaten Tabalong adalah...',
                'option_a' => 'PT Bukit Asam',
                'option_b' => 'PT Kaltim Prima Coal',
                'option_c' => 'PT Newmont',
                'option_d' => 'PT Adaro Indonesia',
                'correct_answer' => 'D',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Komoditas perkebunan rakyat yang paling utama dan menjadi mata pencaharian tradisional warga Tabalong adalah...',
                'option_a' => 'Karet dan Kelapa Sawit',
                'option_b' => 'Cengkeh dan Pala',
                'option_c' => 'Tembakau dan Teh',
                'option_d' => 'Kopi dan Kintamani',
                'correct_answer' => 'A',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Pusat industri semen terbesar di Kalimantan Selatan yang berlokasi di Tabalong adalah Pabrik Semen...',
                'option_a' => 'Semen Gresik',
                'option_b' => 'Semen Conch (PT Tanjung Power / Conch)',
                'option_c' => 'Semen Padang',
                'option_d' => 'Semen Tiga Roda',
                'correct_answer' => 'B',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Buah eksotis khas hutan Tabalong yang mirip buah durian namun berdaging kuning kemerahan adalah...',
                'option_a' => 'Buah Rambutan',
                'option_b' => 'Buah Manggis',
                'option_c' => 'Buah Pampakin / Lai',
                'option_d' => 'Buah Cempedak',
                'correct_answer' => 'C',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Buah langka khas Tabalong yang memiliki rasa asam manis segar dan bentuknya seperti duku adalah...',
                'option_a' => 'Buah Apel',
                'option_b' => 'Buah Kiwi',
                'option_c' => 'Buah Srikaya',
                'option_d' => 'Buah Langsat Tanjung / Kasturi',
                'correct_answer' => 'D',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Kawasan penangkaran bibit ikan air tawar di Tabalong dikembangkan untuk mendukung ketahanan pangan di sektor...',
                'option_a' => 'Perikanan Budidaya (Nila, Patin, Haruan)',
                'option_b' => 'Perikanan Laut',
                'option_c' => 'Peternakan Sapi',
                'option_d' => 'Perkebunan Kopi',
                'correct_answer' => 'A',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Olahan hasil tambang bijih yang diolah untuk bahan konstruksi jalan dan pembangunan di Tabalong adalah...',
                'option_a' => 'Batu Kerikil / Batu Gunung',
                'option_b' => 'Pasir Kuarsa & Batu Split',
                'option_c' => 'Garam Industri',
                'option_d' => 'Kapur Tulis',
                'correct_answer' => 'B',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],
            [
                'card' => 'G',
                'question' => 'Pasar hewan tradisional terbesar untuk perdagangan ternak sapi di Tabalong berada di wilayah...',
                'option_a' => 'Tanjung',
                'option_b' => 'Pugaan',
                'option_c' => 'Kelua',
                'option_d' => 'Muara Uya',
                'correct_answer' => 'C',
                'points' => 400,
                'category' => 'Komoditas Usaha & Sumber Daya Alam',
                'difficulty' => 'Menengah - Sulit',
            ],

            // ==========================================
            // CARD H: Wilayah Administrasi & Pemerintahan (10 Soal)
            // ==========================================
            [
                'card' => 'H',
                'question' => 'Berapakah jumlah kecamatan yang ada di Kabupaten Tabalong saat ini?',
                'option_a' => '10 Kecamatan',
                'option_b' => '8 Kecamatan',
                'option_c' => '15 Kecamatan',
                'option_d' => '12 Kecamatan',
                'correct_answer' => 'D',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Kecamatan di Tabalong yang menjadi pusat perkembangan bisnis baru dan mal pelayanan publik adalah...',
                'option_a' => 'Murung Pudak',
                'option_b' => 'Kelua',
                'option_c' => 'Haruai',
                'option_d' => 'Bintang Ara',
                'correct_answer' => 'A',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Kecamatan yang terletak paling selatan di Kabupaten Tabalong dan berbatasan dengan HSU adalah...',
                'option_a' => 'Jaro',
                'option_b' => 'Pugaan / Kelua',
                'option_c' => 'Muara Uya',
                'option_d' => 'Upau',
                'correct_answer' => 'B',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Kecamatan di wilayah utara Tabalong yang terkenal dengan bentang alam perbukitan dan goa alamnya adalah...',
                'option_a' => 'Tanta',
                'option_b' => 'Tanjung',
                'option_c' => 'Jaro & Muara Uya',
                'option_d' => 'Pugaan',
                'correct_answer' => 'C',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Layanan pengaduan dan tanggap darurat terpadu milik Pemkab Tabalong dapat diakses masyarakat melalui nomor...',
                'option_a' => 'Call Center 112',
                'option_b' => 'Call Center 911',
                'option_c' => 'Call Center 110',
                'option_d' => 'Call Center 119',
                'correct_answer' => 'A',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Program pengentasan kemiskinan dan inovasi pelayanan publik terpadu di Tabalong mengusung semangat...',
                'option_a' => 'Tabalong Mandiri',
                'option_b' => 'Tabalong Smart City / Terdepan',
                'option_c' => 'Tabalong Hijau',
                'option_d' => 'Tabalong Bersatu',
                'correct_answer' => 'B',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Lembaga legislatif daerah yang memegang fungsi pengawasan dan penganggaran di Tabalong adalah...',
                'option_a' => 'DPRD Kabupaten Tabalong',
                'option_b' => 'DPRD Provinsi Kalsel',
                'option_c' => 'DPR RI',
                'option_d' => 'DPD RI',
                'correct_answer' => 'A',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Instansi pemerintah yang bertanggung jawab dalam pengelolaan arsip dan perpustakaan daerah di Tanjung adalah...',
                'option_a' => 'Dinas Pendidikan',
                'option_b' => 'Dinas Perpustakaan dan Kearsipan (Dispersip) Tabalong',
                'option_c' => 'Dinas Kominfo',
                'option_d' => 'Dinas Sosial',
                'correct_answer' => 'B',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Kecamatan pemekaran di Tabalong yang memiliki wilayah hutan cukup luas di sisi barat adalah...',
                'option_a' => 'Bintang Ara',
                'option_b' => 'Kelua',
                'option_c' => 'Pugaan',
                'option_d' => 'Tanta',
                'correct_answer' => 'A',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
            [
                'card' => 'H',
                'question' => 'Pusat pelayanan perizinan terpadu satu pintu di Kabupaten Tabalong dikelola oleh...',
                'option_a' => 'Dinas Perhubungan',
                'option_b' => 'DPM PTSP Tabalong',
                'option_c' => 'Dinas Pekerjaan Umum',
                'option_d' => 'Dinas Kesehatan',
                'correct_answer' => 'B',
                'points' => 500,
                'category' => 'Wilayah Administrasi & Pemerintahan Terkini',
                'difficulty' => 'Sulit',
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}